### ISSUE TITLE
Solidity Developer, ReactJS looking for a team

### ISSUE THREAD

**Issue by obernardovieira** [gitcoinco/beyondblockchainteams#11]
**Classification**
* I'm looking for a team / interesting project ideas.

**Personal Info**
I'm a blockchain developer (almost just ethereum) in a startup. I've been building a few different kinds of dapps. Between projects, I join hackathons (I've won one grants hackathon) and I build tools that I need internally at my work, and then publish them when they are worthy to share.

**Background**
I've been in the development field for a while, curious since I was a kid. I'm now working with solidity, building my own tools and helping others with theirs. I know reactjs as well.

**Links**
My username is always obernardovieira.

**Interested Bounties**
I'm interested in
* Breaking News: Reinventing the Online News Economy
* Saving Lives: Reinventing Healthcare for Web3.0
But I'm also open to others.

**Comment by uivlis** [comment]
Hey @obernardovieira, would be great to have you on board! Check my project idea: https://github.com/gitcoinco/beyondblockchainteams/issues/15.

**Comment by obernardovieira** [comment]
Hi @uivlis nice to see you :clap: 
Sorry, I've joined a team in the meantime.
Appreciate the message. Good luck, see you around :tada:
