### ISSUE TITLE
Subgraph for Lendroid

### ISSUE THREAD

**Issue by tezansahu** [gitcoinco/beyondblockchainteams#24]
**Classification**
* I have a team and an idea.

**Project Idea**

Create a subgraph to index the Lendroid Platform

**Team**

me: @tezansahu

**Eligible Bounties**

The Graph: https://gitcoin.co/issue/graphprotocol/gitcoin-beyond-blockchain-hackathon/1/3176

**Comment by alexvotofuture** [comment]
@tezansahu can you add the "project idea" tag to this issue? Thanks!

**Comment by vs77bb** [comment]
@tezansahu Awesome -- here's a discord channel for you to discuss w/ The Graph reps if you'd like 🙂 https://discord.gg/VaRfcE

**Comment by vs77bb** [comment]
From The Graph folks, as well: 

> Any questions should be directed to our engineering team on our Discord here: https://discord.gg/vtvv7FP in the #hackathons channel. Thanks!

**Comment by tezansahu** [comment]
Cool...Thanks
