### ISSUE TITLE
Looking for a teammate to help me with front-end

### ISSUE THREAD

**Issue by sudeepb02** [gitcoinco/beyondblockchainteams#29]
**Classification**
* I'm looking for a team.

**Personal Info & Background**
* Developer
* C/C++ and other object oriented programming languages
* Solidity

**Interested Bounties**
* Subgraph
I've already started with the subgraph project, and looking for a team mate to help me with the front-end, which will interface with the GraphQL API

**Comment by michaelcohen716** [comment]
@sudeepb02 could be interested in helping you on the front end. what's the best way to contact you?

**Comment by sudeepb02** [comment]
Hi @michaelcohen716 
If you're on discord, that'd be great. Can you confirm if michaelcohen716 your discord handle? I see that you recently joined the graphprotocol server.

**Comment by michaelcohen716** [comment]
yup!

**Comment by Greg-Johns** [comment]
Hi @sudeepb02 let me know how I can help

**Comment by sudeepb02** [comment]
Hi @michaelcohen716 

Can you please confirm if you'd be working on this? 

I'd be working on the Cryptokitties Smart contract for the subgraph, I've gone through the Graph docs once, and set up a simple subgraph for this one as well. Need to add how and what data is collected.

The idea is to analyze how people spend on the gaming platform, how much they earn, and the overall interaction of users with the Cryptokitties gaming platform.

The front-end job would be to get the data from GraphQL API, and display the data in form of graphs and charts, so that it is easy to analyze. Please check this [issue](https://github.com/graphprotocol/gitcoin-beyond-blockchain-hackathon/issues/1) for more details.

**Comment by sudeepb02** [comment]
Project submitted for the Hackathon [here](https://github.com/sudeepb02/cryptokitties-salesauction). Closing this issue.
Thanks @michaelcohen716 for the great work.
Thanks @Greg-Johns for the interest :)
