### ISSUE TITLE
Looking for a team

### ISSUE THREAD

**Issue by ajmachado** [gitcoinco/beyondblockchainteams#3]
**Classification**
I'm looking for a team / interesting project ideas.

**Personal Info & Background**
I'm a beginner blockchain developer. I have recently graduated from Udacity's blockchain developer nanodegree program. As part of the course, I have worked on developing Dapps on the Ethereum network using Solidity, Web3Js, Truffle, Ganache, etc. 

**Links**
https://github.com/ajmachado

**Interested Bounties**

**Comment by howy1993** [comment]
hey - I've been in the space for 2+ years, have played around with contracts and recently picked up some js. I've an idea for the media bounty, wanna team up?

**Comment by ajmachado** [comment]
> hey - I've been in the space for 2+ years, have played around with contracts and recently picked up some js. I've an idea for the media bounty, wanna team up?

Sure! Would love to learn more about the project idea.

**Comment by howy1993** [comment]
So I’m thinking a platform for debating and we bring in experts weekly to debate against each other re: coins and issues. Ideally we bring in crypto/foundation CEOs and pit them against each other or something

I rly like the idea of serious debating - as someone without domain knowledge you can extract a lot of learning cos experts knows the right questions to ask each other. Eventually you can have something like Ethereum vs shitcoin, shitcoin vs shitcoin etc and have these CEOs tear into each other. I don't think we have enough proper debates going on in the space, twitter clashes are too slow for anything to happen

Incentive wise, something like $1k to a foundation/gitcoin grant of the winning debater’s choice would probably be sufficient. For the platform, participants watching the debates can stake crypto in support of a debater, and the winner of debate is the one that has with most value staked in support of him/her

Staking is the fun part of the platform I rly wanna build. Ideally if we have a competent team, we should try routing users stake into some liquidity pool (Compound etc). It generates revenue for the platform, but more importantly I think DeFi-integrated dapps are the future and its gr8 to get some exposure to something like this thru building one

Just came up with this 12h ago when I found out about the hackathon, happy to revise it/change gears if you have any suggestions for improvements or a better idea. Either way if u wanna team up, lets discuss more on https://discord.gg/kvdysu
