### ISSUE TITLE
Team: Nodewaste

### ISSUE THREAD

**Issue by Orami** [gitcoinco/beyondblockchainteams#7]
Hey, hackers!

This is team 
### Nodewaste. 

Nodewaste is a zero waste iot solution. 

the first demo can be found [here](https://github.com/NOde-Waste/nodewaste) at the team github page. we have a demo made with react. 

The basis of the app is to meet a very specific goal of municipalities. increase diversion and reduce contamination. at scale.

Nodewaste diverts material headed to landfil instead to a processing facility that will repurpose material and reward user.

this simple method is repeated across a gamut of campaigns or projects hosted by recovery vendors business or communities.

**Comment by gloriaojuks** [comment]
How do I join this team please?

**Comment by Orami** [comment]
you are joined. team discussion is on the discord channel ill post link

**Comment by Orami** [comment]
discord link https://discordapp.com/invite/TxRKTn8
